<?php
/**
 * Created by PhpStorm.
 * User: rosl
 * Date: 29.12.16
 * Time: 14:49
 */

namespace app\models;


use yii\helpers\ArrayHelper;

class Profile extends \dektrium\user\models\Profile
{


    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            'phoneString' => [['phone'], 'string']
        ]); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'phone'=>\Yii::t('user', 'Телефон')
        ]); // TODO: Change the autogenerated stub
    }


}